import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.2s ease-out',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      colors: {
        'surface': '#fbf9fa',
        'surface-dim': '#dbd9db',
        'surface-bright': '#fbf9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f4',
        'surface-container': '#efedef',
        'surface-container-high': '#e9e7e9',
        'surface-container-highest': '#e4e2e3',
        'on-surface': '#1b1c1d',
        'on-surface-variant': '#44474c',
        'inverse-surface': '#303032',
        'inverse-on-surface': '#f2f0f2',
        'outline': '#74777d',
        'outline-variant': '#c4c6cd',
        'surface-tint': '#4f6073',
        'primary': '#041627',
        'on-primary': '#ffffff',
        'primary-container': '#1a2b3c',
        'on-primary-container': '#8192a7',
        'inverse-primary': '#b7c8de',
        'secondary': '#48626e',
        'on-secondary': '#ffffff',
        'secondary-container': '#cbe7f5',
        'on-secondary-container': '#4e6874',
        'tertiary': '#211200',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#38260b',
        'on-tertiary-container': '#a88c69',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d2e4fb',
        'primary-fixed-dim': '#b7c8de',
        'on-primary-fixed': '#0b1d2d',
        'on-primary-fixed-variant': '#38485a',
        'secondary-fixed': '#cbe7f5',
        'secondary-fixed-dim': '#afcbd8',
        'on-secondary-fixed': '#021f29',
        'on-secondary-fixed-variant': '#304a55',
        'tertiary-fixed': '#feddb5',
        'tertiary-fixed-dim': '#e1c29b',
        'on-tertiary-fixed': '#281802',
        'on-tertiary-fixed-variant': '#584326',
        'background': '#fbf9fa',
        'on-background': '#1b1c1d',
        'surface-variant': '#e4e2e3',
        'critical': '#E53935',
        'success': '#43A047',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '32px',
        xl: '48px',
        gutter: '16px',
        margin: '24px',
      },
      fontFamily: {
        'inter': ['Inter', 'sans-serif'],
        'display-data': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-data': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-bold': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}

export default config
